# Generated by Django 5.2.5 on 2026-01-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='is_quiz_passed',
            field=models.BooleanField(default=False),
        ),
    ]
