# Generated by Django 6.0.1 on 2026-01-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.ManyToManyField(blank=True, related_name="required_for", to="courses.course"),
        ),
    ]
